(library
 (name real_estate_lib)
 (modules revenue opex capex debt property)
 (libraries orcaset)
 (wrapped false))

(executable
 (name run_property)
 (public_name run_property)
 (modules run_property)
 (libraries real_estate_lib orcaset unix))

(executable
 (name run_portfolio)
 (public_name run_portfolio)
 (modules run_portfolio)
 (libraries real_estate_lib orcaset unix))
